### ISSUE TITLE
Useless parameter in NSD edit

### ISSUE THREAD

**Issue by marcellom** [openbaton/dashboard#110]
Catalogue -> NS descriptors -> Action -> Edit

Allowing to edit the value "hbVersion" it makes no effects and no sense in my opinion. Please remove this parameter.
![screen shot 2018-01-12 at 14 48 37](https://user-images.githubusercontent.com/14921749/34877838-f78f3af6-f7a7-11e7-8fd4-c9dcdfb3f7e4.png)

**Comment by lorenzotomasini** [comment]
Also `shared`

Please check all edits. `hbVersion`, `projectId` etc cannot be modified!
