### ISSUE TITLE
Add page for history of actions

### ISSUE THREAD

**Issue by lorenzotomasini** [openbaton/dashboard#111]
Add a page in the admin section that shows the list of executed action, already retrievable by `GET /api/v1/history`

**Comment by Mr-ZohaibHassan** [comment]
![history](https://user-images.githubusercontent.com/8872102/34986152-c88635a4-fab6-11e7-9493-a66ee011135a.png)

**Comment by lorenzotomasini** [comment]
Comments:
* Timestamp would be better if more user friendly
* would be good to be able to filter by column
* id is useless

**Comment by Mr-ZohaibHassan** [comment]
Updated as per comments:
![image](https://user-images.githubusercontent.com/8872102/35100995-31ce7d66-fc5e-11e7-8704-d5c74e949dae.png)
