### ISSUE TITLE
3.1 MB of Js must be loaded for the dashboard

### ISSUE THREAD

**Issue by lorenzotomasini** [openbaton/dashboard#116]
Dashboard needs a cleanup.

it is not possible that our java project has more javascript lines of code than java.

and it is not possible that an user must load 3.1 MB of js for the dashbaord. sometimes OB is used under VPN or bad connection that does not allow fast data transfer making the gui slower than the NFVO

we need a serious refactoring of the dashboard.

**Comment by Mr-ZohaibHassan** [comment]
![jssize](https://user-images.githubusercontent.com/8872102/35231835-1c02582e-ff9a-11e7-981b-88a10158f95b.png)
