### ISSUE TITLE
Delete project empty list

### ISSUE THREAD

**Issue by marcellom** [openbaton/dashboard#12]
1) If you click the button Action of the project you are currently in, it shows an empty list: 
![screen shot 2016-07-21 at 16 44 15](https://cloud.githubusercontent.com/assets/14921749/17027134/faed790e-4f62-11e6-9eb5-b20b452983bd.png)
2) If you try to delete it via the checkbox you get the following error: 
![screen shot 2016-07-21 at 16 45 47](https://cloud.githubusercontent.com/assets/14921749/17027157/18bf556a-4f63-11e6-9f8c-14ceff01bc54.png)

My suggestion is to disable the checkbox and the button Action of the project you are currently in.

**Comment by ogozman** [comment]
This commit fixes this issue
https://github.com/openbaton/dashboard/commit/63521b9dd36e79543b104ef147bb54e1d41e3a28

**Comment by marcellom** [comment]
The issue 1 (If you click the button Action of the project you are currently in, it shows an empty list) is fixed, but not the 2 because you can still delete the project from the multiple delete.

**Comment by ogozman** [comment]
Fixed the the second issue here https://github.com/openbaton/dashboard/commit/6e39f2ad1dcb2ab96e0af444c4f8584a38e57d9b
