### ISSUE TITLE
Dashboard allows to create empty configuration parameters

### ISSUE THREAD

**Issue by marcellom** [openbaton/dashboard#122]
![screen shot 2018-03-22 at 12 54 16](https://user-images.githubusercontent.com/14921749/37769241-9f40cd7e-2dd0-11e8-84ef-2ecc31dfaa0f.png)

**Comment by ogozman** [comment]
fixed here 
https://github.com/openbaton/dashboard/commit/4ab418c089d72237bd984c6f5c2b86eeb2592ad4
