### ISSUE TITLE
NSR remains visible after deletion

### ISSUE THREAD

**Issue by marcellom** [openbaton/dashboard#14]
After deleting a NSR (button ACTION->DELETE), the green success message appears but the NSR remains there. If you refresh the page it disappears, but it is not how it should be.

Suggestion: showing a "loading screen" till the NSR is deleted.

**Comment by ogozman** [comment]
There is no way of knowing if the NSR can be deleted unless you actually try, there might be resources assigned to it inside the NFVO, the VNFM might not be available or something else. This is why "showing a "loading screen" till the NSR is deleted" might send you into the unending loop.
