### ISSUE TITLE
NS Records always show error state

### ISSUE THREAD

**Issue by StanOnix** [openbaton/dashboard#2]
I'm trying to deploy my first VNFs by following the instructions for deployment at the io website. I'm using openstack (devstack) as a VIM and after the upload of the VNFDescriptor I launched it and it worked and provided me an id and tell me that the NSRecord was created but his state is always "ERROR".  When I go into NSRecord and try to launch the VNFDescriptors I also have an error. 
![screenshot from 2016-04-26 11 58 47](https://cloud.githubusercontent.com/assets/10755693/14814376/4afdfece-0ba6-11e6-902a-0810bb602db1.png)

![screenshot from 2016-04-26 11 43 44](https://cloud.githubusercontent.com/assets/10755693/14814280/f25aed18-0ba5-11e6-8f73-b2bfbaa04d3c.png)
Can anyone can help me please ? I even don't know where to find the logs for debugging :/

Thanks,

**Comment by StanOnix** [comment]
I thought that it was a compatibility issue, because I used Vagrant and Virtualbox to deploy my devstack environment and so the VNF (which have to run a qcow2 ubuntu image ) don't boot. Then, I uploaded a qcow2 image in openstack and defined it as the  image on which my VNFs have to run but I have the same error.

**Comment by lorenzotomasini** [comment]
Hi,

The problem is on the VM, not in the dashboard. So I suggest to check the cloud-init output log to see where is the problem 

Cheers,
Lorenzo Tomasini
