### ISSUE TITLE
Display Error mesages

### ISSUE THREAD

**Issue by lorenzotomasini** [openbaton/dashboard#33]
When an error occurs i suggest to display it better, not just the json body that spring returns.

in case of internal error you can display something like: "Sorry there was an internal error, probably is a wrong exception handling, please report to us and we will fix it as soon as possible" not just as in the following pic:
 
![screen shot 2016-12-12 at 18 32 13](https://cloud.githubusercontent.com/assets/3480153/21109474/937a77f6-c099-11e6-8834-f51da7a4c0f2.png)

**Comment by ogozman** [comment]
Done.
