### ISSUE TITLE
Drag & Drop window not uploading files

### ISSUE THREAD

**Issue by gianpietro1** [openbaton/dashboard#51]
Hi, 

I'm testing version 3.2.0 and I'm having problems uploading files through the drag & drop window, either by clicking on it, then browsing, or by actually dragging&dropping the file.
The upload process stays in 0%, like the attached picture shows.

![image 2](https://cloud.githubusercontent.com/assets/10046142/23366925/8637e3ac-fcd6-11e6-9007-f42b91fd51f9.png)

I'm using Chrome Version 56.0.2924.87 (64-bit), also tested with an incognito window and other browsers, still the same problem, nothing happens when trying to upload TAR files to VNF Manager.

[Here](https://www.youtube.com/watch?v=ofTAIXg0QwQ&feature=youtu.be) you can see a video showing the issue and showing the browser console. Regarding the 'failed to execute arc' error at the console, I think it's unrelated as it only appears when the console window is active and I try to resize it.

thanks!

**Comment by mpauls** [comment]
The package is somehow not compressed in the correct way as shown below:
```
tar -tvf iperf-client.tar
drwxr-xr-x  0 ob     ob          0 24 Feb 05:52 iperf-client/
-rw-r--r--  0 ob     ob        402 24 Feb 05:46 iperf-client/Metadata.yaml
-rw-r--r--  0 ob     ob        847 24 Feb 05:46 iperf-client/vnfd.json
```

and actually must look like this:
```
tar -tvf client.tar
-rw-r--r--  0 mpa    staff     124 23 Feb 23:49 Metadata.yaml
drwxr-xr-x  0 mpa    staff       0 13 Dez 17:00 scripts/
-rwxr-xr-x  0 mpa    staff     336 13 Dez 17:00 scripts/server_sipp_start.sh
-rw-r--r--  0 mpa    staff     194 13 Dez 17:00 scripts/sipp_install.sh
-rw-r--r--  0 mpa    staff    3612 13 Jan 09:43 vnfd.json
```

So one way of package it correctly is to go inside the root folder of the package and issue something like this:
`
tar -xvf ../client.tar *
`

**Comment by gc4rella** [comment]
Hi @gianpietro1, sorry for not replying on the users mailing list about this issue. Actually the loading bar becomes green while pressing the send all button, which means packages are actually sent to the NFVO. So, I don't see this as a bug. In addition, check the suggestion from @mpauls about the package structure. A VNF package should have scripts included in its folder. The link to a github is not supported yet in case of VNF packages.

**Comment by gianpietro1** [comment]
Hi @gc4rella, no problem! just posted here just because I thought it would help you better for documentation.
Thanks for your observations @gc4rella & @mpauls , and sorry about missing them! it works fine now, thanks! will confirm through the users mailing list as well.
