### ISSUE TITLE
multiple connection points are displayed when multiple VNFCs are contained in VNFD

### ISSUE THREAD

**Issue by gc4rella** [openbaton/dashboard#62]
when a VNFD contains multiple VNFCs, the dashboard shows multiple connection points for the VDU, which is not correct. 

![screenshot 2017-03-28 13 14 34](https://cloud.githubusercontent.com/assets/4677363/24402414/c80ad08e-13b8-11e7-8054-fb7619618d4a.png)

**Comment by Mr-ZohaibHassan** [comment]
Issue resolved:
01- Connection point and version column are removed from vdu table.
02- Deployment flavor is moved in above table instead of a tab.

https://github.com/openbaton/dashboard/commit/a2c5c2a71973d0f47916469223a6af9647e77973
