### ISSUE TITLE
ShowError method

### ISSUE THREAD

**Issue by Rizwan-Qamar** [openbaton/dashboard#70]
**showError** method is not consistent. In some controllers, it takes data as the first parameter and in some status. ShowError method is not working at many places because of the mismatch.

```
error(function (data, status) {
                console.error('STATUS: ' + status + ' DATA: ' + data);
                showError(status, JSON.stringify(data));
            });
```

**Comment by Mr-ZohaibHassan** [comment]
Resolved:
https://github.com/openbaton/dashboard/commit/7fe90b596f0201935b6dd78f82eb9aeb61e03cc1
