### ISSUE TITLE
Drop down menu changes location when project name is long

### ISSUE THREAD

**Issue by marcellom** [openbaton/dashboard#78]
When you create a project with a long name, the relative drop down menu goes on top of the user one.

![screen shot 2017-06-07 at 10 06 36](https://user-images.githubusercontent.com/14921749/26868638-008e4cd6-4b6a-11e7-834e-02035d158d89.png)

I think it should only shift to the left.

**Comment by marcellom** [comment]
@zohaibhassan122 I am supposed to close the issue, because I opened it. Just a reminder for the next time.

**Comment by Mr-ZohaibHassan** [comment]
Sure, No problem at all.
Actually mostly, I used to close all the issues assigned to me "myself".
That's why i did this as usual.
