### ISSUE TITLE
Add NSD -> Create NSD Menu has VNFDs Name and Type values inverted

### ISSUE THREAD

**Issue by flaviomu** [openbaton/dashboard#79]
When you want to manually create a NSD from GUI and you have to chose the VNFDs, the "Name" and "Type" value are inverted: i.e. the "Name" parameter contains the "Type" value.

 
![openbatonguiissue](https://user-images.githubusercontent.com/14196218/26883213-c0bdc194-4b9c-11e7-9fba-a21c02f24403.png)

**Comment by marcellom** [comment]
Tested
