### ISSUE TITLE
Lifecycle event history not chronologically ordered

### ISSUE THREAD

**Issue by marcellom** [openbaton/dashboard#81]
The lifecycle event history is not chronologically ordered. It is displayed in NSR->VNFR->"lifecycle event history" (tab). The list of events should be chronologically ordered, instead I think it is alphabetically ordered by ID.

**Comment by Mr-ZohaibHassan** [comment]
Issue is resolved, I have tested as well. For further reference please have a look on attached screenshots.
![lifecycle executed at](https://user-images.githubusercontent.com/8872102/27284145-c4f758ec-54f7-11e7-9025-38ccf85ecbc1.png)
![lifecycle](https://user-images.githubusercontent.com/8872102/27284144-c4f4023c-54f7-11e7-8adf-0969eb096289.png)

**Comment by marcellom** [comment]
One question, what is the column "Executed at" in the first screenshot for? I don't see it in my dashboard

**Comment by Mr-ZohaibHassan** [comment]
@marcellom  It was just to show show you that if you want to see chronologically order, this is the sequence from backend, it was just a double a check to verify chronologically order.

**Comment by marcellom** [comment]
ok, tested.
