### ISSUE TITLE
Undefined code:406 when you don't provide Role in Service creation

### ISSUE THREAD

**Issue by marcellom** [openbaton/dashboard#86]
When you create a new service and forget to provide the role, you get this error. I suggest to provide a "default" value for the role or a more useful error message.

![screen shot 2017-11-01 at 18 24 40](https://user-images.githubusercontent.com/14921749/32287806-3d3d60e0-bf32-11e7-85c2-d74dd36c8000.png)

**Comment by marcellom** [comment]
Are there news here?

**Comment by Mr-ZohaibHassan** [comment]
@marcellom I will look on this issue on Monday.
