### ISSUE TITLE
Can not login OpenBaton

### ISSUE THREAD

**Issue by lapnd** [openbaton/dashboard#92]
Hi,
I'm trying to install OpenBaton from binary as the guide http://openbaton.github.io/documentation/nfvo-installation-deb/
However, when trying to access the dashboard, it shows nothing, just blank page.
Inspect the page, It seems something missing
![image](https://user-images.githubusercontent.com/17825933/33422518-8a46d2be-d5e8-11e7-844e-42649a8b419b.png)

I tried with the latest version as well as version 5.0.0 but no luck.
Can you please give me a suggestion to workaround this?
Thank you!

**Comment by Mr-ZohaibHassan** [comment]
@lapd-viosoft Somehow this error belongs to your Web Browser. There could be some browser extensions that can interrupt the rendering of java-script like firebug,  bypass proxy, VPN or any other extension.
Try to use it in incognito mode or in a different web browser. I hope this would solve your issue.

**Comment by lapnd** [comment]
Thank for your support,
I used VPN to connect to OpenBaton VM on another location. I tried with different browsers (and different machine, still use VPN) but the issue is not solved.
I have to rebuild nfvo with updating dashboard/src/main/resources/static/js/libs/require/require.js
from waitSeconds: 7 to waitSeconds: 0 (to disable timeout) and I can work with Openbaton now!
